#!/usr/bin/env bash
# Installs and configures HAproxy to load balance web-01 and web-02

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 44.203.152.117:80 check
    server web-02 54.167.139.121:80 check
HAPROXY

echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
