#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx and custom X-Served-By response header

apt-get update -y
apt-get install -y nginx

cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By $hostname;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

service nginx restart
