#!/usr/bin/env bash
# This script fixes Nginx to listen on port 80 of all active IPv4 IPs

sudo apt-get install -y nginx
sudo sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
